In [17]:
import pandas as pd

# Leer el archivo
file = pd.read_csv("./datos_ejercicios/datos_ejercicio3.csv")
# file

In [18]:
# 1. Obtener las primeras 3 filas: 
file.head(3)

  Unnamed: 0   nombre  puntaje  intentos califico
0          a    Oliva     11.5         1       Sí
1          b  Daniela      8.0         3       No
2          c     Juan     15.5         2       Sí

In [19]:
# 2. Obtener las últimas 5 filas
file.tail()

  Unnamed: 0  nombre  puntaje  intentos califico
5          f    Alex     19.0         3       Sí
6          g   Julio     13.5         1       Sí
7          h   Edgar      NaN         1       No
8          i   Angie      8.0         2       No
9          j  Irlesa     18.0         1       Sí

In [20]:
# 3. Realiza el procesamiento que muestre el siguiente resultado y escribe un comentario con el prompt del ejercicio
file[["Unnamed: 0","nombre", "califico"]]

  Unnamed: 0   nombre califico
0          a    Oliva       Sí
1          b  Daniela       No
2          c     Juan       Sí
3          d   Germán       No
4          e   Edward       No
5          f     Alex       Sí
6          g    Julio       Sí
7          h    Edgar       No
8          i    Angie       No
9          j   Irlesa       Sí

In [21]:
# 4. Realiza el procesamiento que muestre el siguiente resultado y escribe un comentario con el prompt del ejercicio
file.iloc[[1, 4], [1,4]]

    nombre califico
1  Daniela       No
4   Edward       No

In [22]:
file.loc[[1, 4], ["nombre", "califico"] ]

    nombre califico
1  Daniela       No
4   Edward       No

In [23]:
# 5. Seleccionar los registros que tienen un campo NaN
file[file["puntaje"].isnull()]

  Unnamed: 0  nombre  puntaje  intentos califico
3          d  Germán      NaN         3       No
7          h   Edgar      NaN         1       No

In [24]:
file["puntaje"].isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
Name: puntaje, dtype: bool

In [25]:
# 6. Seleccionar registros donde los valores de una columna estén en un rango y denel siguiente resultado. Escribe un comentario con el prompt del ejercicio
file[file["puntaje"].between(13,19)]

  Unnamed: 0  nombre  puntaje  intentos califico
2          c    Juan     15.5         2       Sí
5          f    Alex     19.0         3       Sí
6          g   Julio     13.5         1       Sí
9          j  Irlesa     18.0         1       Sí

In [26]:
# 7. Encontrar los datos que no son nulos
file.notna()

   Unnamed: 0  nombre  puntaje  intentos  califico
0        True    True     True      True      True
1        True    True     True      True      True
2        True    True     True      True      True
3        True    True    False      True      True
4        True    True     True      True      True
5        True    True     True      True      True
6        True    True     True      True      True
7        True    True    False      True      True
8        True    True     True      True      True
9        True    True     True      True      True

In [27]:
# 9. Sumar los valores de la columna intentos
sumaIntentos=file["intentos"].sum()
print("suma: ",sumaIntentos)

suma:  19

In [28]:
# 10. Calcular el promedio de los valores de la columna intentos
promedioIntentos = file["intentos"].mean()

In [29]:
# 11. Reemplazar valores de una columna califico, como se muestra a continuación y escribe un comentario con el prompt del ejercicio
file["califico"] = file["califico"].map({"Sí": True, "No": False})  # Reemplaza los Si por True y No por False
file

  Unnamed: 0   nombre  puntaje  intentos  califico
0          a    Oliva     11.5         1      True
1          b  Daniela      8.0         3     False
2          c     Juan     15.5         2      True
3          d   Germán      NaN         3     False
4          e   Edward      8.0         2     False
5          f     Alex     19.0         3      True
6          g    Julio     13.5         1      True
7          h    Edgar      NaN         1     False
8          i    Angie      8.0         2     False
9          j   Irlesa     18.0         1      True

In [30]:
# 12. Seleccionar registros donde se cumpla una condición para valores de una columna y escribir un comentario con el promt del ejercicio
file[ (file["puntaje"].between(10,19)) ]    # Filtra los puntajes que están entre 10 y 19

  Unnamed: 0  nombre  puntaje  intentos  califico
0          a   Oliva     11.5         1      True
2          c    Juan     15.5         2      True
5          f    Alex     19.0         3      True
6          g   Julio     13.5         1      True
9          j  Irlesa     18.0         1      True