In [3]:
import pandas as pd

# Leer el archivo
file = pd.read_csv("./datos_ejercicios/datos_ejercicio2.csv")
fileLimpio = file.drop("Unnamed: 0", axis="columns")
fileLimpio

   producto  precio  ventas
0  Manzanas    1200    1200
1  Plátanos     800    1500
2     Peras    1500     800
3      Uvas    2000     600
4  Naranjas    1000    1300

In [4]:
# 2. Filtra y muestra las filas donde el precio es mayor de 1000
fileLimpio[fileLimpio["precio"] > 1000]

   producto  precio  ventas
0  Manzanas    1200    1200
2     Peras    1500     800
3      Uvas    2000     600

In [5]:
print(len(fileLimpio))

5

In [6]:
# 3. Añade una nueva columna llamada ventas con los valores [1200, 1500, 800, 600, 1300] 
fileLimpio=fileLimpio.drop("ventas", axis="columns")
fileLimpio["ventas"] = [1200, 1500, 800, 600, 1300]
fileLimpio

   producto  precio  ventas
0  Manzanas    1200    1200
1  Plátanos     800    1500
2     Peras    1500     800
3      Uvas    2000     600
4  Naranjas    1000    1300

In [7]:
# 4. Agrega la columna stock 
fileLimpio["stock"] = [50, 100, 30, 25, 80]
fileLimpio

   producto  precio  ventas  stock
0  Manzanas    1200    1200     50
1  Plátanos     800    1500    100
2     Peras    1500     800     30
3      Uvas    2000     600     25
4  Naranjas    1000    1300     80

In [8]:
# 5. Filtra y muestra las filas donde las ventas son mayores de 1000 
fileLimpio[fileLimpio["ventas"] > 1000]

   producto  precio  ventas  stock
0  Manzanas    1200    1200     50
1  Plátanos     800    1500    100
4  Naranjas    1000    1300     80

In [9]:
# 6. Añade dos nuevas columnas llamadas: iva y precio_bruto, realizar el cálculo del iva con el 19%
#fileLimpio["precio_bruto"] = fileLimpio["precio"] / 1.19    #Precio sin IVA
fileLimpio["precio_bruto"] = fileLimpio["precio"] - fileLimpio["precio"]*0.19

fileLimpio["IVA"] = fileLimpio["precio"] * 0.19
fileLimpio

   producto  precio  ventas  stock  precio_bruto    IVA
0  Manzanas    1200    1200     50         972.0  228.0
1  Plátanos     800    1500    100         648.0  152.0
2     Peras    1500     800     30        1215.0  285.0
3      Uvas    2000     600     25        1620.0  380.0
4  Naranjas    1000    1300     80         810.0  190.0

In [10]:
# 7. Redondea (a 1 o 2 decimales) los datos de las columnas de iva y precio_bruto
fileLimpio["IVA"] = fileLimpio["IVA"].round(2)
fileLimpio["precio_bruto"] = fileLimpio.precio_bruto.round(2)
fileLimpio

   producto  precio  ventas  stock  precio_bruto    IVA
0  Manzanas    1200    1200     50         972.0  228.0
1  Plátanos     800    1500    100         648.0  152.0
2     Peras    1500     800     30        1215.0  285.0
3      Uvas    2000     600     25        1620.0  380.0
4  Naranjas    1000    1300     80         810.0  190.0