In [1]:
import pandas as pd

df=pd.read_csv("datos_twitter.csv")
df

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [2]:
df.loc[5:7, ["id", "user"]]

       id           user
5  183726  mateusmartins
6  183727  leonardokuffo
7  183728    pedrojuarez

In [3]:
df.iloc[5:8, [0,6]]

       id           user
5  183726  mateusmartins
6  183727  leonardokuffo
7  183728    pedrojuarez

In [4]:
df.iloc[25,5]

'MEXICO'

In [5]:
df.loc[25, "country"]

'MEXICO'

In [6]:
df[["country", "id"]]

    country      id
0   ECUADOR  183721
1    BRASIL  183722
2    MEXICO  183723
3   ECUADOR  183724
4    MEXICO  183725
5    BRASIL  183726
6   ECUADOR  183727
7    MEXICO  183728
8    MEXICO  183729
9    BRASIL  183730
10   BRASIL  183731
11   BRASIL  183732
12  ECUADOR  183733
13  ECUADOR  183734
14   MEXICO  183735
15   MEXICO  183736
16   BRASIL  183737
17   MEXICO  183738
18  ECUADOR  183739
19   BRASIL  183740
20  ECUADOR  183741
21  ECUADOR  183742
22   BRASIL  183743
23   BRASIL  183744
24   BRASIL  183745
25   MEXICO  183746
26   BRASIL  183747

In [7]:
df[df["favorites"] >= 490]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822

In [8]:
df[df["favorites"] >= 490][["country", "id"]]

  country      id
1  BRASIL  183722
5  BRASIL  183726

In [9]:
df[df["country"] == "BRASIL"]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [10]:
df[df.retweets == 21]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822

In [14]:
copia = df.rename(columns={"full_text": "fullt 2text"})
copia

,id,fullt 2text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [15]:
df

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [24]:
df[((df.country == "BRASIL") | (df.country == "MEXICO")) & (df.mentions <= 30)]

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [26]:
df.full_text.str.contains("love")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26    False
Name: full_text, dtype: bool