In [137]:
import pandas as pd

file = pd.read_csv("netflix.csv")

In [138]:
# Comprobacion de campos nulos
forma1= file.isnull().any()
forma2=file.isnull().sum()

print(forma1)
print("-------------")
print(forma2)

User_ID              False
Name                 False
Age                  False
Country              False
Subscription_Type    False
Watch_Time_Hours     False
Favorite_Genre       False
Last_Login           False
dtype: bool
-------------
User_ID              0
Name                 0
Age                  0
Country              0
Subscription_Type    0
Watch_Time_Hours     0
Favorite_Genre       0
Last_Login           0
dtype: int64

In [139]:
# Se introduce un NaN para experimentar
file.loc[1,"Age"] = pd.NA
file.loc[1]

User_ID                        2
Name                 John Miller
Age                          NaN
Country                      USA
Subscription_Type        Premium
Watch_Time_Hours          321.75
Favorite_Genre            Sci-Fi
Last_Login            2025-02-05
Name: 1, dtype: object

In [140]:
file

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18.0,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,NaN,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60.0,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44.0,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68.0,USA,Standard,909.30,Drama,2025-01-14
...,...,...,...,...,...,...,...,...
24995,24996,David Miller,18.0,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17.0,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14.0,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71.0,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19.0,Germany,Premium,207.06,Documentary,2024-04-12

In [141]:
file.iloc[1]

User_ID                        2
Name                 John Miller
Age                          NaN
Country                      USA
Subscription_Type        Premium
Watch_Time_Hours          321.75
Favorite_Genre            Sci-Fi
Last_Login            2025-02-05
Name: 1, dtype: object

In [142]:
# Cambiar el NaN  tras haberlo introducido
file["Age"]=file["Age"].fillna(3)

In [143]:
# Borrar un valor con NaN
file.dropna()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18.0,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,3.0,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60.0,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44.0,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68.0,USA,Standard,909.30,Drama,2025-01-14
...,...,...,...,...,...,...,...,...
24995,24996,David Miller,18.0,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17.0,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14.0,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71.0,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19.0,Germany,Premium,207.06,Documentary,2024-04-12

In [144]:
#Agrupar por distintos atributos
agrupacionPorNombre = file.groupby("Name")
horasVistasAcumuladas = agrupacionPorNombre.Watch_Time_Hours.sum()

agrupacionPorSuscripcion = file.groupby("Subscription_Type")
suscritosPorCategoria = agrupacionPorSuscripcion.Name.count()

agrupacionPorPais = file.groupby("Country")
paisesMasCinefilos = agrupacionPorPais.Watch_Time_Hours.sum()

agrupacionPorGenero = file.groupby("Favorite_Genre")
GenerosMasVistos = agrupacionPorGenero.Watch_Time_Hours.sum()

print("horas vistas acumuladas: ", horasVistasAcumuladas)
print("suscriptores por categoría: ", suscritosPorCategoria)

horas vistas acumuladas:  Name
Alex Brown        129562.96
Alex Davis        125602.07
Alex Garcia       134256.62
Alex Hernandez    135483.15
Alex Johnson      124854.48
                    ...
Sarah Jones       123377.62
Sarah Martinez    126774.83
Sarah Miller      119511.56
Sarah Smith       122056.31
Sarah Williams    129772.71
Name: Watch_Time_Hours, Length: 100, dtype: float64
suscriptores por categoría:  Subscription_Type
Basic       8356
Premium     8402
Standard    8242
Name: Name, dtype: int64

In [145]:
horasVistasAcumuladas.reset_index()

              Name  Watch_Time_Hours
0       Alex Brown         129562.96
1       Alex Davis         125602.07
2      Alex Garcia         134256.62
3   Alex Hernandez         135483.15
4     Alex Johnson         124854.48
..             ...               ...
95     Sarah Jones         123377.62
96  Sarah Martinez         126774.83
97    Sarah Miller         119511.56
98     Sarah Smith         122056.31
99  Sarah Williams         129772.71

[100 rows x 2 columns]

In [146]:
suscritosPorCategoria.reset_index()

  Subscription_Type  Name
0             Basic  8356
1           Premium  8402
2          Standard  8242

In [147]:
paisesMasCinefilos.reset_index()

     Country  Watch_Time_Hours
0  Australia        1238500.79
1     Brazil        1261391.37
2     Canada        1273443.87
3     France        1251435.06
4    Germany        1259665.39
5      India        1233067.52
6      Japan        1215774.50
7     Mexico        1237744.23
8         UK        1285800.67
9        USA        1254898.05

In [148]:
# Ordenar los datos
suscritosPorCategoriaOrdenado = suscritosPorCategoria.sort_values(ascending=False)
categoriaMayor = suscritosPorCategoriaOrdenado.head(1)

paisesMasCinefilosOrdenado = paisesMasCinefilos.sort_values(ascending=False)
paisMasCinefilo = paisesMasCinefilosOrdenado.head(1)

GenerosMasVistosOrdenado = GenerosMasVistos.sort_values(ascending=False)
GeneroMasVisto = GenerosMasVistosOrdenado.head(1)

In [149]:
paisesMasCinefilosOrdenado

Country
UK           1285800.67
Canada       1273443.87
Brazil       1261391.37
Germany      1259665.39
USA          1254898.05
France       1251435.06
Australia    1238500.79
Mexico       1237744.23
India        1233067.52
Japan        1215774.50
Name: Watch_Time_Hours, dtype: float64

In [150]:
copia = file.head(10)
agrupacionPorPais = file.groupby(["Country"])
agrupacionPorPais["Age"].max()

Country
Australia    80.0
Brazil       80.0
Canada       80.0
France       80.0
Germany      80.0
India        80.0
Japan        80.0
Mexico       80.0
UK           80.0
USA          80.0
Name: Age, dtype: float64