In [2]:
import pandas as pd

# Leer el archivo
file = pd.read_csv("netflix.csv")

In [3]:
# 1. Muestra las 10 primeras filas del dataframe. 
copia = file.head(10)
copia

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14
5,6,David Johnson,21,USA,Standard,615.93,Romance,2025-02-03
6,7,John Hernandez,57,Canada,Standard,755.47,Romance,2025-01-05
7,8,Katie Hernandez,68,USA,Standard,145.23,Sci-Fi,2024-10-30
8,9,James Williams,39,UK,Basic,950.14,Action,2024-04-16
9,10,Alex Davis,55,Mexico,Standard,696.66,Horror,2024-07-03

In [4]:
# 2. Agrupa los datos por tipo de suscripción y muestra cuántos usuarios están suscritos a cada tipo. 
# (Los resultados de la siguiente imagen se obtienen de las primeras 10 filas del dataframe)  
agrupacionPorSuscripcion = copia.groupby("Subscription_Type")
suscritos = agrupacionPorSuscripcion["Name"].count()
suscritos

Subscription_Type
Basic       2
Premium     3
Standard    5
Name: Name, dtype: int64

In [5]:
# 3. Aplica reset_index en el resultado anterior para obtener el siguiente resultado:
suscritos.reset_index()

  Subscription_Type  Name
0             Basic     2
1           Premium     3
2          Standard     5

In [6]:
# 4. Muestra el tipo de suscripción que más usuarios tiene.
suscritosOrdenado = suscritos.sort_values(ascending=False)
mayorSuscripcion = suscritosOrdenado.head(1)

mayorSuscripcion

Subscription_Type
Standard    5
Name: Name, dtype: int64

In [7]:
# 5. Agrupa el dataframe por país y obtén la persona de mayor edad por cada país, después ordena el resultado de mayor a menor. 
agrupacionPorPais = copia.groupby("Country")
agrupacionPorPaisOrdenada = agrupacionPorPais["Age"].max().sort_values(ascending=False)

agrupacionPorPaisOrdenada

Country
USA       68
UK        60
Canada    57
Mexico    55
France    18
Name: Age, dtype: int64

In [8]:
# 6. Muestra cuál es el país con la persona de mayor edad. 
paisMasViejo = agrupacionPorPaisOrdenada.head(1)
paisMasViejo

Country
USA    68
Name: Age, dtype: int64

In [9]:
# 7. Agrupa el dataframe por género favorito y muestra el total de horas de visualización por cada género, ordenar de mayor a menor.
agrupacionPorGenero = copia.groupby("Favorite_Genre")
agrupacionPorGeneroOrdenada = agrupacionPorGenero["Watch_Time_Hours"].sum().sort_values(ascending=False)

agrupacionPorGeneroOrdenada

Favorite_Genre
Romance        1371.40
Drama           989.56
Action          950.14
Horror          696.66
Sci-Fi          466.98
Documentary     261.56
Comedy           35.89
Name: Watch_Time_Hours, dtype: float64

In [10]:
# 8. Muestra cuál es el género que más se ve. 
generoMasVisto = agrupacionPorGeneroOrdenada.head(1)
generoMasVisto

Favorite_Genre
Romance    1371.4
Name: Watch_Time_Hours, dtype: float64

In [11]:
# 9. Muestra el total de horas de visualización de cada género por país y ordena la tabla de mayor a menor. 
agrupacionPorPaisYGenero  = copia.groupby(["Country", "Favorite_Genre"])
horasVistasPorPais=agrupacionPorPaisYGenero.Watch_Time_Hours.sum().sort_values(ascending=False)

horasVistasPorPais.reset_index()

  Country Favorite_Genre  Watch_Time_Hours
0      UK         Action            950.14
1     USA          Drama            909.30
2  Canada        Romance            755.47
3  Mexico         Horror            696.66
4     USA        Romance            615.93
5     USA         Sci-Fi            466.98
6     USA    Documentary            261.56
7  France          Drama             80.26
8      UK         Comedy             35.89

In [12]:
# 10. Elimina los países duplicados del resultado anterior para obtener el género que más se ve en cada país y ordena los resultados de mayor a menor. 
generoMasVistoPorPais = horasVistasPorPais.reset_index().drop_duplicates(subset=["Country"], keep='first')
generoMasVistoPorPais

  Country Favorite_Genre  Watch_Time_Hours
0      UK         Action            950.14
1     USA          Drama            909.30
2  Canada        Romance            755.47
3  Mexico         Horror            696.66
7  France          Drama             80.26

In [ ]:
# 11. Encuentra el usuario que más ve películas de terror.
agrupacionPorNombreYGenero = file.groupby(["Name", "Favorite_Genre"])
horasVistasPorUsuario = agrupacionPorNombreYGenero.Watch_Time_Hours.sum()
horasVistasPorUsuario = horasVistasPorUsuario.reset_index()

usuariosMasLocos = horasVistasPorUsuario[horasVistasPorUsuario["Favorite_Genre"] == "Horror"].sort_values(by="Watch_Time_Hours", ascending=False)
usuarioMasLoco = usuariosMasLocos.head(1)
usuarioMasLoco

                 Name Favorite_Genre  Watch_Time_Hours
627  Michael Williams         Horror           26553.5

In [14]:
# 12. Convierte los datos de la columna Last_login de texto a tipo fecha-hora con el siguiente código:  
file.Last_Login = pd.to_datetime(file.Last_Login)
file

# Ahora agrega las columnas: dia, mes y año al dataframe:
file["dia"] = pd.DatetimeIndex(file.Last_Login).day
file["mes"] = pd.DatetimeIndex(file.Last_Login).month
file["año"] = pd.DatetimeIndex(file.Last_Login).year

file

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,dia,mes,año
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12,12,5,2024
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05,5,2,2025
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24,24,1,2025
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25,25,3,2024
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14,14,1,2025
...,...,...,...,...,...,...,...,...,...,...,...
24995,24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18,18,1,2025
24996,24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29,29,6,2024
24997,24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16,16,10,2024
24998,24999,Michael Williams,71,USA,Basic,655.89,Action,2024-08-27,27,8,2024
24999,25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12,12,4,2024

In [15]:
# 13. Muestra cuál es el género más visto en cada mes sin importar el año.
agrupacionPorGeneroYMes = file.groupby(["Favorite_Genre", "mes"])
horasDeGeneroPorMes = agrupacionPorGeneroYMes.Watch_Time_Hours.sum()
horasDeGeneroPorMes.reset_index().sort_values(by=["mes", "Watch_Time_Hours"],ascending=[True, False]).drop_duplicates(subset=["mes"], keep='first')

   Favorite_Genre  mes  Watch_Time_Hours
24    Documentary    1         155234.37
37          Drama    2         151636.89
14         Comedy    3         161148.20
51         Horror    4         158675.21
28    Documentary    5         168337.57
41          Drama    6         150928.32
54         Horror    7         164243.17
67        Romance    8         170530.55
20         Comedy    9         160113.97
9          Action   10         176453.95
70        Romance   11         161195.14
23         Comedy   12         159646.38

In [16]:
# 14. Muestra el género más visto en cada año
agrupacionPorAñoYGenero = file.groupby(["año", "Favorite_Genre"])
horasDeGeneroPorAño = agrupacionPorAñoYGenero.Watch_Time_Hours.sum().sort_values(ascending=False)

GeneroMasVistoPorAño = horasDeGeneroPorAño.groupby("año").head(1)
GeneroMasVistoPorAño.reset_index()

    año Favorite_Genre  Watch_Time_Hours
0  2024    Documentary        1486174.93
1  2025         Horror         344383.06

In [17]:
# 15. Haga un top 3 de los géneros que más ven los menores de edad en el mes de diciembre sin importar el año.
agrupacionPorGeneroYEdad = file.groupby(["Favorite_Genre", "Age", "mes"])
horasVistasPorEdad = agrupacionPorGeneroYEdad.Watch_Time_Hours.sum()

#Filtro por menores de edad
horasVistasPorEdad = horasVistasPorEdad.reset_index()
horasVistasPorNiños = horasVistasPorEdad[ (horasVistasPorEdad["Age"] < 18) & (horasVistasPorEdad["mes"] == 12) ]

# Filtro por género
horasVistasPorGenero = horasVistasPorNiños.groupby("Favorite_Genre")
top3GenerosMasVistosPorNiñosEnDiciembre = horasVistasPorGenero.Watch_Time_Hours.sum().sort_values(ascending=False).head(3)
top3GenerosMasVistosPorNiñosEnDiciembre.reset_index()

  Favorite_Genre  Watch_Time_Hours
0          Drama          14072.92
1         Comedy          13993.87
2         Action          13362.20